# partitioning 1
part1:
    volume-groups:
        - device: /dev/sda
          name: OS
          parts:
              - name: ROOT
                size: 1024
                mount-point: /
              - name: USR
                size: 5120
                mount-point: /usr
              - name: VAR
                size: 5120
                mount-point: /var
                grow: true
        - device: /dev/sdb
          name: DATA
          parts:
              - name: DATA
                size: 1024
                mount-point: /var/data
                grow: true

# partitioning 2
part2:
    volume-groups:
        - device: /dev/sda
          name: OS
          parts:
              - name: ROOT
                size: 1024
                mount-point: /
              - name: USR
                size: 4096
                mount-point: /usr
              - name: VAR
                size: 5120
                mount-point: /var
                grow: true
