language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: 
  - pip install -e . --use-mirrors
# command to run tests
script: "./run_test.sh"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f3b4eb316df520a150eb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # default: false

